apiVersion: apps/v1
kind: Deployment
metadata:
  name:  chat-backend
spec:
  replicas: 2
  selector:
      matchLabels:
        app:  chat-backend
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: chat-backend
    spec:     # pod spec                  
      containers: 
      - name: 
        image: us.icr.io/cldstd31-ns/node-web-app:latest # image we pushed
        ports:
          - containerPort: 8080
        env:
          - name: APIKEY
            value: D7ECw0pntdQAiVkJusrdWRvNH9xqHiSdJoNSo2NnD5Be
          - name: URL
            value: https://api.us-south.assistant.watson.cloud.ibm.com/instances/fce076b9-8103-4e56-82ed-270eb33d699f
          - name: ASSISTANT_ID
            value: 83a3bcd6-bdae-419d-b4d6-2247535b7f6f
